/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import dao.DAOemployee;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.employee;


public class vistaEmployee extends javax.swing.JFrame {
    
    String columnas[]= {"N° Iden","Tipo Iden","Nombre 1","Nombre 2","Ape 1","Ape 2","Estado Civ","Genero","Dire","Tele","Cumple"};
    DefaultTableModel modelo = new DefaultTableModel(columnas,0);
    DAOemployee dao = new DAOemployee();
    ArrayList<Object[]> data = new ArrayList<>();
    
    public vistaEmployee() {
        initComponents();
        setLocationRelativeTo(null);
        cargar();
    }
    private void cargar(){
        this.data = dao.consultar();
        modelo.setNumRows(0);
        for(Object [] dato : this.data){
            this.modelo.addRow(dato);
        }
        tblDat.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumdoc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTipdoc = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtNom1 = new javax.swing.JTextField();
        txtNom2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApe1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtApe2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFeccum = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDir = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEstciv = new javax.swing.JComboBox<>();
        txtGen = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnEli = new javax.swing.JButton();
        btnMod = new javax.swing.JButton();
        btbAgr = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDat = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 51));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("n° Documento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));
        jPanel1.add(txtNumdoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 96, -1));

        jLabel2.setText("Tipo Documento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        txtTipdoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(txtTipdoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        jLabel3.setText("Nombre 1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));
        jPanel1.add(txtNom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 120, -1));
        jPanel1.add(txtNom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 98, -1));

        jLabel4.setText("Nombre 2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));
        jPanel1.add(txtApe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 100, -1));

        jLabel5.setText("Apellido 1");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));
        jPanel1.add(txtApe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 93, -1));

        jLabel6.setText("Apellido 2");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));
        jPanel1.add(txtFeccum, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 101, -1));

        jLabel9.setText("Fecha Cumpleaños");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));
        jPanel1.add(txtDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 161, -1));

        jLabel7.setText("Direccion");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));
        jPanel1.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 111, -1));

        jLabel8.setText("Telefono");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        txtEstciv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(txtEstciv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        txtGen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(txtGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        jLabel10.setText("Estado civil");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 73, -1));

        jLabel11.setText("Genero");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        btnEli.setBackground(new java.awt.Color(255, 0, 0));
        btnEli.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        btnEli.setText("ELIMINAR");
        btnEli.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 0), null, null));
        btnEli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliMouseClicked(evt);
            }
        });
        btnEli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliActionPerformed(evt);
            }
        });
        jPanel1.add(btnEli, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 90, 30));

        btnMod.setBackground(new java.awt.Color(255, 255, 51));
        btnMod.setText("MODIFICAR");
        btnMod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 204), null, null));
        btnMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModMouseClicked(evt);
            }
        });
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });
        jPanel1.add(btnMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 100, 30));

        btbAgr.setBackground(new java.awt.Color(51, 255, 51));
        btbAgr.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btbAgr.setText("AGREGAR");
        btbAgr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 255, 0), null, null));
        btbAgr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btbAgrMouseClicked(evt);
            }
        });
        btbAgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbAgrActionPerformed(evt);
            }
        });
        jPanel1.add(btbAgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 80, 30));

        tblDat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 578, 200));

        jLabel13.setFont(new java.awt.Font("Sitka Display", 0, 30)); // NOI18N
        jLabel13.setText("Institución Universitaria Digital de Antioquia");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 570, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 6, 590, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbAgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbAgrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbAgrActionPerformed

    private void btnEliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliActionPerformed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModActionPerformed

    private void btbAgrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbAgrMouseClicked
        // TODO add your handling code here:
        employee emp = new employee(Integer.parseInt(txtNumdoc.getText()),
                                    txtTipdoc.getSelectedIndex(),
                                    txtNom1.getText(),
                                    txtNom2.getText(),
                                    txtApe1.getText(),
                                    txtApe2.getText(),
                                    txtEstciv.getSelectedIndex(),
                                    txtGen.getSelectedIndex(),
                                    txtDir.getText(),
                                    txtTel.getText(),
                                    txtFeccum.getText()
                                    );
        if(dao.insertar(emp)){
            JOptionPane.showMessageDialog(this,"Exito al insertar registro");
        }else{
            JOptionPane.showMessageDialog(this,"Error al insertar ");
        }
        cargar();
    }//GEN-LAST:event_btbAgrMouseClicked

    private void tblDatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatMouseClicked
        // TODO add your handling code here:
        this.txtNumdoc.setText(tblDat.getValueAt(tblDat.getSelectedRow(), 0).toString());
        //this.txtTipdoc.setText(tblDat.getValueAt(tblDat.getSelectedRow(), 1).toString());
        this.txtNom1.setText(tblDat.getValueAt(tblDat.getSelectedRow(), 2).toString());
        this.txtNom2.setText(tblDat.getValueAt(tblDat.getSelectedRow(), 3).toString());
        this.txtApe1.setText(tblDat.getValueAt(tblDat.getSelectedRow(), 4).toString());
        this.txtApe2.setText(tblDat.getValueAt(tblDat.getSelectedRow(), 5).toString());
        //this.txtEstciv.setText(tblDat.getValueAt(tblDat.getSelectedRow(), 6).toString());
        //this.txtGen.setText(tblDat.getValueAt(tblDat.getSelectedRow(), 7).toString());
        this.txtDir.setText(tblDat.getValueAt(tblDat.getSelectedRow(), 8).toString());
        this.txtTel.setText(tblDat.getValueAt(tblDat.getSelectedRow(), 9).toString());
        this.txtFeccum.setText(tblDat.getValueAt(tblDat.getSelectedRow(), 10).toString());
        
    }//GEN-LAST:event_tblDatMouseClicked

    private void btnModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModMouseClicked
        // TODO add your handling code here:
        employee emp = new employee(Integer.parseInt(txtNumdoc.getText()),
                                    txtTipdoc.getSelectedIndex(),
                                    txtNom1.getText(),
                                    txtNom2.getText(),
                                    txtApe1.getText(),
                                    txtApe2.getText(),
                                    txtEstciv.getSelectedIndex(),
                                    txtGen.getSelectedIndex(),
                                    txtDir.getText(),
                                    txtTel.getText(),
                                    txtFeccum.getText()
                                    );
        if(dao.modificar(emp)){
            JOptionPane.showMessageDialog(this,"Exito almodificar registro");
        }else{
            JOptionPane.showMessageDialog(this,"Error al Modificar");
        }
        cargar();
        
    }//GEN-LAST:event_btnModMouseClicked

    private void btnEliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliMouseClicked
        // TODO add your handling code here:
        employee emp = new employee(Integer.parseInt(txtNumdoc.getText()),
                                    txtTipdoc.getSelectedIndex(),
                                    txtNom1.getText(),
                                    txtNom2.getText(),
                                    txtApe1.getText(),
                                    txtApe2.getText(),
                                    txtEstciv.getSelectedIndex(),
                                    txtGen.getSelectedIndex(),
                                    txtDir.getText(),
                                    txtTel.getText(),
                                    txtFeccum.getText()
                                    );
        if(dao.eliminar(emp)){
            JOptionPane.showMessageDialog(this,"Exito al eliminar registro");
        }else{
            JOptionPane.showMessageDialog(this,"Error al Eliminar");
        }
        cargar();
        
    }//GEN-LAST:event_btnEliMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbAgr;
    private javax.swing.JButton btnEli;
    private javax.swing.JButton btnMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDat;
    private javax.swing.JTextField txtApe1;
    private javax.swing.JTextField txtApe2;
    private javax.swing.JTextField txtDir;
    private javax.swing.JComboBox<String> txtEstciv;
    private javax.swing.JTextField txtFeccum;
    private javax.swing.JComboBox<String> txtGen;
    private javax.swing.JTextField txtNom1;
    private javax.swing.JTextField txtNom2;
    private javax.swing.JTextField txtNumdoc;
    private javax.swing.JTextField txtTel;
    private javax.swing.JComboBox<String> txtTipdoc;
    // End of variables declaration//GEN-END:variables
}
